# This file was generated by GoReleaser. DO NOT EDIT.
cask "legible" do
  name "legible"
  desc "Sync documents from reMarkable tablet with OCR text layer generation"
  homepage "https://github.com/platinummonkey/legible"
  version "1.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "legible"

  on_macos do
    on_intel do
      url "https://github.com/platinummonkey/legible/releases/download/v#{version}/legible_#{version}_darwin_x86_64.tar.gz"
      sha256 "33ae5359e3d0d17fcc7d83b79df61f5d5f0ec5373a3199fe6456f518dec0463b"
    end
    on_arm do
      url "https://github.com/platinummonkey/legible/releases/download/v#{version}/legible_#{version}_darwin_arm64.tar.gz"
      sha256 "778abc61895e87a990db2bf1f5ab6a1a1872cc6fdbdc06cb120c36beaf9b8106"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/platinummonkey/legible/releases/download/v#{version}/legible_#{version}_linux_x86_64.tar.gz"
      sha256 "b284e882cafd4124848729f8733da2c2ac78a5e8426736fb9058442a1167d7fb"
    end
    on_arm do
      url "https://github.com/platinummonkey/legible/releases/download/v#{version}/legible_#{version}_linux_arm64.tar.gz"
      sha256 "3f5b613b059420e96e29891931554df4e5ba60bbe7f020a75fd5000328c138e4"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/legible"]
    end
  end

  caveats do
    "Legible requires a reMarkable tablet with cloud sync enabled."
    ""
    "Optional: Install Ollama for OCR text layer generation (searchable PDFs):"
    "  brew install ollama"
    "  ollama pull llava"
    ""
    "Get started:"
    "  1. Authenticate: legible auth"
    "  2. Sync documents: legible sync"
    ""
    "Documentation: https://github.com/platinummonkey/legible"
  end

  # No zap stanza required
end
