# This file was generated by GoReleaser. DO NOT EDIT.
cask "legible" do
  name "legible"
  desc "Sync documents from reMarkable tablet with OCR text layer generation"
  homepage "https://github.com/platinummonkey/legible"
  version "1.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "legible"

  on_macos do
    on_intel do
      url "https://github.com/platinummonkey/legible/releases/download/v#{version}/legible_#{version}_darwin_x86_64.tar.gz"
      sha256 "f8563d726c19b5e8db36e0228e0f636d90c33e30099a8e413c7af601170e0f91"
    end
    on_arm do
      url "https://github.com/platinummonkey/legible/releases/download/v#{version}/legible_#{version}_darwin_arm64.tar.gz"
      sha256 "d08b1df7a1f53c05d29740eabf5c84965540a0b06e1330d33631a3462a94d96d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/platinummonkey/legible/releases/download/v#{version}/legible_#{version}_linux_x86_64.tar.gz"
      sha256 "cbacae039ca09acab1be87ab575985c1808b606a0990b2bca3d55177edc6bb4b"
    end
    on_arm do
      url "https://github.com/platinummonkey/legible/releases/download/v#{version}/legible_#{version}_linux_arm64.tar.gz"
      sha256 "ec7d3d534abffc4c5ad1010b69cd271a150ade20e74422490b4b8daeebaa7d55"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/legible"]
    end
  end

  caveats do
    "Legible requires a reMarkable tablet with cloud sync enabled."
    ""
    "Optional: Install Ollama for OCR text layer generation (searchable PDFs):"
    "  brew install ollama"
    "  ollama pull llava"
    ""
    "Get started:"
    "  1. Authenticate: legible auth"
    "  2. Sync documents: legible sync"
    ""
    "Documentation: https://github.com/platinummonkey/legible"
  end

  # No zap stanza required
end
