# This file was generated by GoReleaser. DO NOT EDIT.
cask "legible" do
  name "legible"
  desc "Sync documents from reMarkable tablet with OCR text layer generation"
  homepage "https://github.com/platinummonkey/legible"
  version "1.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "legible"

  on_macos do
    on_intel do
      url "https://github.com/platinummonkey/legible/releases/download/v#{version}/legible_#{version}_darwin_x86_64.tar.gz"
      sha256 "33bfef048ba653f3ab80384deac5d306e1a1daab450123fb618d4cb767f4c03c"
    end
    on_arm do
      url "https://github.com/platinummonkey/legible/releases/download/v#{version}/legible_#{version}_darwin_arm64.tar.gz"
      sha256 "95321b7037a004b23ba2dc248c058a8b6ce4d602aa42a1180edf8885766fac65"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/platinummonkey/legible/releases/download/v#{version}/legible_#{version}_linux_x86_64.tar.gz"
      sha256 "62d12e524a7760bd03f986795a39b34e01c30a98af365a22c56dc030e0e67fa2"
    end
    on_arm do
      url "https://github.com/platinummonkey/legible/releases/download/v#{version}/legible_#{version}_linux_arm64.tar.gz"
      sha256 "d752ebecedb07fb215030b2f28bf576c31af8bea452eac3a602dcb8a16e1a05c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/legible"]
    end
  end

  caveats do
    "Legible requires a reMarkable tablet with cloud sync enabled."
    ""
    "Optional: Install Ollama for OCR text layer generation (searchable PDFs):"
    "  brew install ollama"
    "  ollama pull llava"
    ""
    "Get started:"
    "  1. Authenticate: legible auth"
    "  2. Sync documents: legible sync"
    ""
    "Documentation: https://github.com/platinummonkey/legible"
  end

  # No zap stanza required
end
